/*
* AUTOGENERATED FILE
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))=
        "****************"  // placeholder for beggining
        "20260622T193231"   // DateTime using ISO-8601 format
        " "                 // alignment
        "fa85f499"          // STLIB commit
        "--------"          // ADJ commit
        "3eb427bd"          // Board commit
        // the '=' is used for unparsing
        ;
}