/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20260208T180214"   // DateTime using ISO-8601 format
        " "                 // alignment
        "d1a09c97"          // STLIB commit
        "--------"          // ADJ commit
        "e123fa46"          // Board commit
        // the '=' is used for unparsing
        ;
}