/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20260123T211535"   // DateTime using ISO-8601 format
        " "                 // alignment
        "332e04d7"          // STLIB commit
        "--------"          // ADJ commit
        "134d8429"          // Board commit
        // the '=' is used for unparsing
        ;
}