#pragma once
#include "ST-LIB.hpp"

//Data packets for {{board}} -AUTOGENERATED CODE, DO NOT MODIFY-
struct DataPackets{
    {% for enum in enums -%}
    enum class {{enum.name}} : uint8_t 
    {
    {%- for value in enum["values"] %}
        {{value}} = {{loop.index0}},
    {%- endfor %}
    };
    {% endfor %}

private:
    
    {% for packet in packets -%}
    static void {{packet.name}}_init({% for variable in packet.variables %}{{variable.type}} &{{variable.name}}{% if not loop.last %}, {% endif %}{% endfor %})
    {
        {{packet.name}} = new HeapPacket(static_cast<uint16_t>({{packet.id}}){% if packet.variables %}, {% for variable in packet.variables %}&{{variable.name}}{% if not loop.last %}, {% endif %}{% endfor %}{% endif %});
    }
    {% endfor -%}

    {% set sending_count = sending_packets|length %}
    {% if sending_count <= 32 %}
    using FlagsType = uint32_t;
    #define CTZ_FUNC __builtin_ctz
    {% elif sending_count <= 64 %}
    using FlagsType = uint64_t;
    #define CTZ_FUNC __builtin_ctzll
    {% else %}
    #error "Too many sending tasks (>64)"
    {% endif %}

    inline static volatile FlagsType send_flags{0};

    {% for packet in sending_packets %}
    static void send_task_{{loop.index0}}() {
        {% if packet.name is string -%}
        DataPackets::{{packet.socket}}->send_packet(*DataPackets::{{packet.name}});
        {% else %}
        {% for name in packet.name -%}
        DataPackets::{{packet.socket}}->send_packet(*DataPackets::{{name}});
        {% endfor -%}
        {%- endif %}
    }
    {% endfor %}

    using SendAction = void(*)();
    static inline SendAction send_actions[] = {
        {% for packet in sending_packets %}
        send_task_{{loop.index0}},
        {% endfor %}
    };

public:
    {%for packet in packets -%}
    inline static HeapPacket *{{packet.name}}{nullptr};
    {% endfor %}
    {% for socket in sockets -%}
    inline static {{socket.type}} *{{socket.name}}{nullptr};
    {% endfor %}
        
    static void start()
    {   
        {% for packet in packets -%}
        if ({{packet.name}} == nullptr) {
            ErrorHandler("Packet {{packet.name}} not initialized");
        }
        {% endfor %}

        {% for socket in ServerSockets -%}
        {{socket.name}} = new ServerSocket("{{socket.board_ip}}",{{socket.port}});
        {%- endfor %}
        {% for socket in DatagramSockets -%}
        {{socket.name}} = new DatagramSocket("{{socket.board_ip}}",{{socket.port}},"{{socket.remote_ip}}",{{socket.port}});
        {% endfor %}
        {% for socket in Sockets -%}
        {{socket.name}} = new Socket("{{socket.board_ip}}",{{socket.local_port}},"{{socket.remote_ip}}",{{socket.remote_port}});
        {% endfor %}
        
        {%- for packet in sending_packets %}
        Scheduler::register_task({% if packet.period_type == "ms" %}{{ (packet.period*1000)|round|int }}{% else %}{{ packet.period|round|int }}{% endif %}, +[](){
            DataPackets::send_flags |= (static_cast<FlagsType>(1) << {{loop.index0}});
        }); {%- endfor %}
    }

    static void update()
    {
        while(DataPackets::send_flags) {
            uint8_t index = CTZ_FUNC(DataPackets::send_flags);
            DataPackets::send_flags &= ~(static_cast<FlagsType>(1) << index);
            if (index < {{sending_count}}) {
                DataPackets::send_actions[index]();
            }
        }
    }

   
};