#pragma once
#include "ST-LIB.hpp"

//Order packets for {{board}} -AUTOGENERATED CODE, DO NOT MODIFY-

{% for packet in packets -%}
extern void {{packet.name}}_cb();
{% endfor %}
class OrderPackets{
public:
    {% for enum in enums -%}
    enum class {{enum.name}} : uint8_t {
    {%- for value in enum["values"] %}
        {{value}} = {{loop.index0}},
    {%- endfor %}
    };
    {% endfor %}

    OrderPackets() = default;

    {% for packet in packets -%}
    static HeapOrder *{{packet.name}};
    {% endfor %}
    
    {% for packet in packets -%}
    static void {{packet.name}}_init({% for variable in packet.variables %}{{variable.type}} &{{variable.name}}{% if not loop.last %}, {% endif %}{% endfor %}){
        {{packet.name}} = new HeapOrder({{packet.id}}, &{{packet.name}}_cb{% if packet.variables %}, {% for variable in packet.variables %}&{{variable.name}}{% if not loop.last %}, {% endif %}{% endfor %}{% endif %});
    }
    {% endfor %}
};