#pragma once
#include "ST-LIB.hpp"

//Order packets for {{board}} -AUTOGENERATED CODE, DO NOT MODIFY-

class OrderPackets{
    public:
    {% for enum in enums %}enum class {{enum.name}}:uint8_t
    {
    {% for value in enum["values"] %}{{value}}={{loop.index0}}{%if not loop.last%},{%endif%}
    {% endfor %}};

    {% endfor %}
    
    {%for packet in packets%} inline static bool {{packet.name}}_flag{false};
    {% endfor %}

    private:
        uint32_t id{0};
        
    {%for packet in packets%}static void {{packet.name}}_cb(){
        {{packet.name}}_flag = true;
    }
    {% endfor %}
    public:
        {%for packet in packets%}HeapOrder* {{packet.name}};
        {% endfor %}
        
    OrderPackets({%for value in data %}{{value.type}} &{{value.name}}{%if not loop.last%},{%endif%}{%endfor%})
{

    {% for packet in packets %}{{packet.name}}=new HeapOrder({{packet.id}},&{{packet.name}}_cb{% if packet.data%},{{packet.data}}{% endif%});
    {% endfor %}
}
};
