#pragma once
#include "ST-LIB.hpp"

/*Data packets for VCU 
-AUTOGENERATED CODE, DO NOT MODIFY-*/
class DataPackets{
public:
    enum class general_state : uint8_t 
    {
        CONNECTING = 0,
        OPERATIONAL = 1,
        FAULT = 2,
    };
    enum class operational_state : uint8_t 
    {
        IDLE = 0,
        END_OF_RUN = 1,
        ENERGIZED = 2,
        READY = 3,
        DEMONSTRATION = 4,
        RECOVERY = 5,
    };
    enum class reed1 : uint8_t 
    {
        UNDEPLOYED = 0,
        DEPLOYED = 1,
    };
    enum class reed2 : uint8_t 
    {
        UNDEPLOYED = 0,
        DEPLOYED = 1,
    };
    enum class reed3 : uint8_t 
    {
        UNDEPLOYED = 0,
        DEPLOYED = 1,
    };
    enum class reed4 : uint8_t 
    {
        UNDEPLOYED = 0,
        DEPLOYED = 1,
    };
    enum class flow1 : uint8_t 
    {
        OFF = 0,
        ON = 1,
    };
    enum class flow2 : uint8_t 
    {
        OFF = 0,
        ON = 1,
    };
    enum class tape_enable_output : uint8_t 
    {
        DISABLED = 0,
        ENABLED = 1,
    };
    enum class emergency_tape : uint8_t 
    {
        EMERGENCY_SECTION = 0,
        NORMAL_SECTION = 1,
    };
    enum class SDC : uint8_t 
    {
        OFF = 0,
        ON = 1,
    };
    
    
    static void Current_State_init(general_state &general_state, operational_state &operational_state)
    {
        Current_State_packet = new HeapPacket(static_cast<uint16_t>(249), &general_state, &operational_state);
    }
    
    static void Reeds_init(reed1 &reed1, reed2 &reed2, reed3 &reed3, reed4 &reed4, bool &all_reeds)
    {
        Reeds_packet = new HeapPacket(static_cast<uint16_t>(251), &reed1, &reed2, &reed3, &reed4, &all_reeds);
    }
    
    static void Flow_init(flow1 &flow1, flow2 &flow2)
    {
        Flow_packet = new HeapPacket(static_cast<uint16_t>(250), &flow1, &flow2);
    }
    
    static void Regulator_init(float &regulator_1_pressure, float &regulator_2_pressure)
    {
        Regulator_packet = new HeapPacket(static_cast<uint16_t>(252), &regulator_1_pressure, &regulator_2_pressure);
    }
    
    static void Pressure_init(float &pressure_high, float &pressure_regulator, float &pressure_brakes, float &pressure_capsule)
    {
        Pressure_packet = new HeapPacket(static_cast<uint16_t>(253), &pressure_high, &pressure_regulator, &pressure_brakes, &pressure_capsule);
    }
    
    static void tapes_init(tape_enable_output &tape_enable_output, emergency_tape &emergency_tape)
    {
        tapes_packet = new HeapPacket(static_cast<uint16_t>(254), &tape_enable_output, &emergency_tape);
    }
    
    static void sdc_init(SDC &SDC)
    {
        sdc_packet = new HeapPacket(static_cast<uint16_t>(255), &SDC);
    }
    
    static void recovery_state_init(uint8_t &state)
    {
        recovery_state_packet = new HeapPacket(static_cast<uint16_t>(65), &state);
    }
    
    public:
    inline static HeapPacket *Current_State_packet{nullptr};
    inline static HeapPacket *Reeds_packet{nullptr};
    inline static HeapPacket *Flow_packet{nullptr};
    inline static HeapPacket *Regulator_packet{nullptr};
    inline static HeapPacket *Pressure_packet{nullptr};
    inline static HeapPacket *tapes_packet{nullptr};
    inline static HeapPacket *sdc_packet{nullptr};
    inline static HeapPacket *recovery_state_packet{nullptr};
    
    inline static DatagramSocket *control_station_udp{nullptr};
    inline static DatagramSocket *pcu_udp{nullptr};
    inline static DatagramSocket *hvscu_udp{nullptr};
    
        
    static void start()
    {   
        if (Current_State_packet == nullptr) {
            ErrorHandler("Packet Current_State not initialized");
        }
        if (Reeds_packet == nullptr) {
            ErrorHandler("Packet Reeds not initialized");
        }
        if (Flow_packet == nullptr) {
            ErrorHandler("Packet Flow not initialized");
        }
        if (Regulator_packet == nullptr) {
            ErrorHandler("Packet Regulator not initialized");
        }
        if (Pressure_packet == nullptr) {
            ErrorHandler("Packet Pressure not initialized");
        }
        if (tapes_packet == nullptr) {
            ErrorHandler("Packet tapes not initialized");
        }
        if (sdc_packet == nullptr) {
            ErrorHandler("Packet sdc not initialized");
        }
        if (recovery_state_packet == nullptr) {
            ErrorHandler("Packet recovery_state not initialized");
        }
        

        control_station_udp = new DatagramSocket("192.168.1.3",50400,"192.168.0.9",50400);
        pcu_udp = new DatagramSocket("192.168.1.3",50402,"192.168.1.5",50402);
        hvscu_udp = new DatagramSocket("192.168.1.3",50403,"192.168.1.7",50403);
        
        Scheduler::register_task(16670, +[](){
            DataPackets::control_station_udp->send_packet(*DataPackets::Current_State_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::Flow_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::Pressure_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::tapes_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::sdc_packet);
            DataPackets::pcu_udp->send_packet(*DataPackets::recovery_state_packet);
            });
        Scheduler::register_task(17, +[](){
            DataPackets::control_station_udp->send_packet(*DataPackets::Reeds_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::Regulator_packet);
            });
    }


   
};