#pragma once
#include "ST-LIB.hpp"

/*Data packets for PCU
-AUTOGENERATED CODE, DO NOT MODIFY-*/

#ifndef ARRAY_LEN
#define ARRAY_LEN(Arr) (sizeof(Arr)/sizeof(Arr[0]))
#endif
class DataPackets{
public:
    enum class state : uint8_t
    {
        Connecting = 0,
        Idle = 1,
        Accelerating = 2,
        Fault = 3,
    };
    
#ifdef STLIB_ETH
    static void PWM_init(uint32_t &frequency, float &modulation_frequency, float &duty_u, float &duty_v, float &duty_w)
    {
        PWM_packet = new StackPacket(static_cast<uint16_t>(550), &frequency, &modulation_frequency, &duty_u, &duty_v, &duty_w);
    }

    static void Batteries_Voltage_init(float &voltage_battery_a, float &voltage_battery_b)
    {
        Batteries_Voltage_packet = new StackPacket(static_cast<uint16_t>(551), &voltage_battery_a, &voltage_battery_b);
    }

    static void Current_Sensors_init(float &current_sensor_u_a, float &current_sensor_v_a, float &current_sensor_w_a, float &current_sensor_u_b, float &current_sensor_v_b, float &current_sensor_w_b, float &current_Peak, float &error_pi, float &target_voltage, float &svpwm_time, float &imod)
    {
        Current_Sensors_packet = new StackPacket(static_cast<uint16_t>(552), &current_sensor_u_a, &current_sensor_v_a, &current_sensor_w_a, &current_sensor_u_b, &current_sensor_v_b, &current_sensor_w_b, &current_Peak, &error_pi, &target_voltage, &svpwm_time, &imod);
    }

    static void State_Machine_States_init(state &state)
    {
        State_Machine_States_packet = new StackPacket(static_cast<uint16_t>(553), &state);
    }

    static void Speed_Data_init(float &target_speed, double &speed_error, float &actual_current_ref, float &slip_motor, double &imu_speed_km_h, float &imu_position_m)
    {
        Speed_Data_packet = new StackPacket(static_cast<uint16_t>(555), &target_speed, &speed_error, &actual_current_ref, &slip_motor, &imu_speed_km_h, &imu_position_m);
    }

    static void Gate_Driver_Reporting_init(bool &gd_fault_a, bool &gd_fault_b, bool &gd_ready_a, bool &gd_ready_b)
    {
        Gate_Driver_Reporting_packet = new StackPacket(static_cast<uint16_t>(558), &gd_fault_a, &gd_fault_b, &gd_ready_a, &gd_ready_b);
    }

    #endif

public:
#ifdef STLIB_ETH
    inline static Packet *PWM_packet{nullptr};
    inline static Packet *Batteries_Voltage_packet{nullptr};
    inline static Packet *Current_Sensors_packet{nullptr};
    inline static Packet *State_Machine_States_packet{nullptr};
    inline static Packet *Speed_Data_packet{nullptr};
    inline static Packet *Gate_Driver_Reporting_packet{nullptr};
    

    inline static uint32_t group_0_idx = 0;
    inline static Packet **group_0[] = { &PWM_packet, &Batteries_Voltage_packet, &Current_Sensors_packet, &State_Machine_States_packet, &Speed_Data_packet, &Gate_Driver_Reporting_packet };
    

    inline static DatagramSocket *control_station_udp{nullptr};
    
#endif

    static void start()
    {
#ifdef STLIB_ETH
        if (PWM_packet == nullptr) {
            PANIC("Packet PWM not initialized");
        }
        if (Batteries_Voltage_packet == nullptr) {
            PANIC("Packet Batteries_Voltage not initialized");
        }
        if (Current_Sensors_packet == nullptr) {
            PANIC("Packet Current_Sensors not initialized");
        }
        if (State_Machine_States_packet == nullptr) {
            PANIC("Packet State_Machine_States not initialized");
        }
        if (Speed_Data_packet == nullptr) {
            PANIC("Packet Speed_Data not initialized");
        }
        if (Gate_Driver_Reporting_packet == nullptr) {
            PANIC("Packet Gate_Driver_Reporting not initialized");
        }
        

        control_station_udp = new DatagramSocket("192.168.1.5",50400,"192.168.0.9",50400);
        
        Scheduler::register_task(16670 / ARRAY_LEN(DataPackets::group_0), +[](){
            Packet *packet = *DataPackets::group_0[DataPackets::group_0_idx];
            DataPackets::control_station_udp->send_packet(*packet);
            DataPackets::group_0_idx = (DataPackets::group_0_idx + 1) % ARRAY_LEN(DataPackets::group_0);
        });
#endif
    }



};