#pragma once
#include "ST-LIB.hpp"

//Data packets for PCU -AUTOGENERATED CODE, DO NOT MODIFY-
class DataPackets{
    public:
    enum class general_state_machine:uint8_t
    {
    Connecting=0,
    Operational=1,
    Fault=2
    };

    enum class operational_state_machine:uint8_t
    {
    IDLE=0,
    Braking=1,
    Accelerating=2,
    Regenerative=3
    };

    enum class space_vector_active:uint8_t
    {
    DISABLE=0,
    ACTIVE=1
    };

    enum class current_control_active:uint8_t
    {
    DISABLE=0,
    ACTIVE=1
    };

    enum class speed_control_active:uint8_t
    {
    DISABLE=0,
    ACTIVE=1
    };

    enum class encoder_direction:uint8_t
    {
    Forward=0,
    Backward=1
    };

    

    private:
        inline static uint32_t id{0};
    public:
        static inline HeapPacket* pwm_packet{};
        static inline HeapPacket* Batteries_Voltage{};
        static inline HeapPacket* Current_sensors{};
        static inline HeapPacket* StateMachine_states{};
        static inline HeapPacket* Speetec_data{};
        static inline HeapPacket* Speed_data{};
        static inline HeapPacket* GateDriverReporting{};
        

        static inline ServerSocket* control_station_tcp = nullptr;
        static inline DatagramSocket* control_station_udp = nullptr;
        
        
    DataPackets(uint32_t &frequency,float &modulation_frequency,float &duty_u,float &duty_v,float &duty_w,float &Voltage_Battery_A,float &Voltage_Battery_B,float &current_sensor_u_a,float &current_sensor_v_a,float &current_sensor_w_a,float &current_sensor_u_b,float &current_sensor_v_b,float &current_sensor_w_b,double &current_Peak,double &Error_PI,double &Target_Voltage,float &SVPWM_Time,float &imod,general_state_machine &general_state_machine,operational_state_machine &operational_state_machine,space_vector_active &space_vector_active,current_control_active &current_control_active,speed_control_active &speed_control_active,double &encoder_position,encoder_direction &encoder_direction,double &encoder_speed,double &encoder_speed_km_h,double &encoder_acceleration,float &target_speed,double &speed_error,float &actual_current_ref,bool &gd_fault_a,bool &gd_fault_b,bool &gd_ready_a,bool &gd_ready_b)
{   
    control_station_tcp = new ServerSocket("192.168.1.5",50500);
    
    control_station_udp = new DatagramSocket("192.168.1.5",50400,"192.168.0.9",50400);
    
    
    pwm_packet = new HeapPacket(static_cast<uint16_t>(550),&frequency,&modulation_frequency,&duty_u,&duty_v,&duty_w);

    Batteries_Voltage = new HeapPacket(static_cast<uint16_t>(551),&Voltage_Battery_A,&Voltage_Battery_B);

    Current_sensors = new HeapPacket(static_cast<uint16_t>(552),&current_sensor_u_a,&current_sensor_v_a,&current_sensor_w_a,&current_sensor_u_b,&current_sensor_v_b,&current_sensor_w_b,&current_Peak,&Error_PI,&Target_Voltage,&SVPWM_Time,&imod);

    StateMachine_states = new HeapPacket(static_cast<uint16_t>(553),&general_state_machine,&operational_state_machine,&space_vector_active,&current_control_active,&speed_control_active);

    Speetec_data = new HeapPacket(static_cast<uint16_t>(554),&encoder_position,&encoder_direction,&encoder_speed,&encoder_speed_km_h,&encoder_acceleration);

    Speed_data = new HeapPacket(static_cast<uint16_t>(555),&target_speed,&speed_error,&actual_current_ref);

    GateDriverReporting = new HeapPacket(static_cast<uint16_t>(558),&gd_fault_a,&gd_fault_b,&gd_ready_a,&gd_ready_b);

    
    Scheduler::register_task(16670.0,+[](){
        
        DataPackets::control_station_udp->send_packet(*pwm_packet);
        DataPackets::control_station_udp->send_packet(*Batteries_Voltage);
        DataPackets::control_station_udp->send_packet(*Current_sensors);
        DataPackets::control_station_udp->send_packet(*StateMachine_states);
        DataPackets::control_station_udp->send_packet(*Speetec_data);
        DataPackets::control_station_udp->send_packet(*Speed_data);
        DataPackets::control_station_udp->send_packet(*GateDriverReporting);
        
        
    });
    


}
};