#pragma once
#include "ST-LIB.hpp"

/*Order packets for VCU 
-AUTOGENERATED CODE, DO NOT MODIFY- */


class OrderPackets{
public:
    enum class pump : uint8_t 
    {
        UNIDADES = 0,
        PLACAS = 1,
    };
    enum class regulator : uint8_t 
    {
        REGULATOR_1 = 0,
        REGULATOR_2 = 1,
    };
    enum class run_id : uint8_t 
    {
        LIM = 0,
    };
    enum class motor_direction : uint8_t 
    {
        FORWARD = 0,
        BACKWARDS = 1,
    };
    

    inline static bool Brake_flag{false};
    inline static bool Unbrake_flag{false};
    inline static bool Potencia_Refri_flag{false};
    inline static bool Set_Regulator_flag{false};
    inline static bool Enable_Tapes_flag{false};
    inline static bool Disbable_Tapes_flag{false};
    inline static bool Close_Contactors_flag{false};
    inline static bool Open_Contactors_flag{false};
    inline static bool Levitation_flag{false};
    inline static bool Stop_Levitation_flag{false};
    inline static bool Emergency_Stop_flag{false};
    inline static bool Propulsion_flag{false};
    inline static bool SVPWM_flag{false};
    inline static bool Stop_Motor_flag{false};
    inline static bool Current_Control_flag{false};
    inline static bool Speed_Control_flag{false};
    inline static bool Motor_Brake_flag{false};
    inline static bool Recovery_flag{false};
    

    OrderPackets() = default;

    inline static HeapOrder *Brake_order{nullptr};
    inline static HeapOrder *Unbrake_order{nullptr};
    inline static HeapOrder *Potencia_Refri_order{nullptr};
    inline static HeapOrder *Set_Regulator_order{nullptr};
    inline static HeapOrder *Enable_Tapes_order{nullptr};
    inline static HeapOrder *Disbable_Tapes_order{nullptr};
    inline static HeapOrder *Close_Contactors_order{nullptr};
    inline static HeapOrder *Open_Contactors_order{nullptr};
    inline static HeapOrder *Levitation_order{nullptr};
    inline static HeapOrder *Stop_Levitation_order{nullptr};
    inline static HeapOrder *Emergency_Stop_order{nullptr};
    inline static HeapOrder *Propulsion_order{nullptr};
    inline static HeapOrder *SVPWM_order{nullptr};
    inline static HeapOrder *Stop_Motor_order{nullptr};
    inline static HeapOrder *Current_Control_order{nullptr};
    inline static HeapOrder *Speed_Control_order{nullptr};
    inline static HeapOrder *Motor_Brake_order{nullptr};
    inline static HeapOrder *Recovery_order{nullptr};
    
    
    static void Brake_init()
    {
        Brake_order = new HeapOrder(43, &Brake_cb);
    }
    static void Unbrake_init()
    {
        Unbrake_order = new HeapOrder(52, &Unbrake_cb);
    }
    static void Potencia_Refri_init(uint32_t &duty, pump &pump)
    {
        Potencia_Refri_order = new HeapOrder(33, &Potencia_Refri_cb, &duty, &pump);
    }
    static void Set_Regulator_init(float &regulator_pressure, regulator &regulator)
    {
        Set_Regulator_order = new HeapOrder(34, &Set_Regulator_cb, &regulator_pressure, &regulator);
    }
    static void Enable_Tapes_init()
    {
        Enable_Tapes_order = new HeapOrder(35, &Enable_Tapes_cb);
    }
    static void Disbable_Tapes_init()
    {
        Disbable_Tapes_order = new HeapOrder(36, &Disbable_Tapes_cb);
    }
    static void Close_Contactors_init()
    {
        Close_Contactors_order = new HeapOrder(44, &Close_Contactors_cb);
    }
    static void Open_Contactors_init()
    {
        Open_Contactors_order = new HeapOrder(53, &Open_Contactors_cb);
    }
    static void Levitation_init(float &levitation_distance)
    {
        Levitation_order = new HeapOrder(37, &Levitation_cb, &levitation_distance);
    }
    static void Stop_Levitation_init()
    {
        Stop_Levitation_order = new HeapOrder(46, &Stop_Levitation_cb);
    }
    static void Emergency_Stop_init()
    {
        Emergency_Stop_order = new HeapOrder(55, &Emergency_Stop_cb);
    }
    static void Propulsion_init(run_id &run_id)
    {
        Propulsion_order = new HeapOrder(56, &Propulsion_cb, &run_id);
    }
    static void SVPWM_init(float &modulation_frequency, float &commutation_frequency, float &max_voltage, float &reference_voltage, motor_direction &motor_direction)
    {
        SVPWM_order = new HeapOrder(57, &SVPWM_cb, &modulation_frequency, &commutation_frequency, &max_voltage, &reference_voltage, &motor_direction);
    }
    static void Stop_Motor_init()
    {
        Stop_Motor_order = new HeapOrder(58, &Stop_Motor_cb);
    }
    static void Current_Control_init(float &modulation_frequency, float &commutation_frequency, float &reference_current, float &max_voltage, motor_direction &motor_direction)
    {
        Current_Control_order = new HeapOrder(59, &Current_Control_cb, &modulation_frequency, &commutation_frequency, &reference_current, &max_voltage, &motor_direction);
    }
    static void Speed_Control_init(float &reference_speed, float &commutation_frequency, float &max_voltage, motor_direction &motor_direction)
    {
        Speed_Control_order = new HeapOrder(60, &Speed_Control_cb, &reference_speed, &commutation_frequency, &max_voltage, &motor_direction);
    }
    static void Motor_Brake_init()
    {
        Motor_Brake_order = new HeapOrder(61, &Motor_Brake_cb);
    }
    static void Recovery_init()
    {
        Recovery_order = new HeapOrder(32, &Recovery_cb);
    }
    

    inline static Socket *pcu_tcp{nullptr};
    inline static Socket *hvscu_tcp{nullptr};
    
    inline static ServerSocket *control_station_tcp{nullptr};
    

    static void start()
    {
        if (Brake_order == nullptr) {
            ErrorHandler("Order Brake not initialized");
        }
        if (Unbrake_order == nullptr) {
            ErrorHandler("Order Unbrake not initialized");
        }
        if (Potencia_Refri_order == nullptr) {
            ErrorHandler("Order Potencia_Refri not initialized");
        }
        if (Set_Regulator_order == nullptr) {
            ErrorHandler("Order Set_Regulator not initialized");
        }
        if (Enable_Tapes_order == nullptr) {
            ErrorHandler("Order Enable_Tapes not initialized");
        }
        if (Disbable_Tapes_order == nullptr) {
            ErrorHandler("Order Disbable_Tapes not initialized");
        }
        if (Close_Contactors_order == nullptr) {
            ErrorHandler("Order Close_Contactors not initialized");
        }
        if (Open_Contactors_order == nullptr) {
            ErrorHandler("Order Open_Contactors not initialized");
        }
        if (Levitation_order == nullptr) {
            ErrorHandler("Order Levitation not initialized");
        }
        if (Stop_Levitation_order == nullptr) {
            ErrorHandler("Order Stop_Levitation not initialized");
        }
        if (Emergency_Stop_order == nullptr) {
            ErrorHandler("Order Emergency_Stop not initialized");
        }
        if (Propulsion_order == nullptr) {
            ErrorHandler("Order Propulsion not initialized");
        }
        if (SVPWM_order == nullptr) {
            ErrorHandler("Order SVPWM not initialized");
        }
        if (Stop_Motor_order == nullptr) {
            ErrorHandler("Order Stop_Motor not initialized");
        }
        if (Current_Control_order == nullptr) {
            ErrorHandler("Order Current_Control not initialized");
        }
        if (Speed_Control_order == nullptr) {
            ErrorHandler("Order Speed_Control not initialized");
        }
        if (Motor_Brake_order == nullptr) {
            ErrorHandler("Order Motor_Brake not initialized");
        }
        if (Recovery_order == nullptr) {
            ErrorHandler("Order Recovery not initialized");
        }
        

        control_station_tcp = new ServerSocket("192.168.1.3",50500);
        pcu_tcp = new Socket("192.168.1.3",50501,"192.168.1.5",50500);
        hvscu_tcp = new Socket("192.168.1.3",50502,"192.168.1.7",50500);
        
    }

private:
    static void Brake_cb()
    {
        Brake_flag = true;
    }
    static void Unbrake_cb()
    {
        Unbrake_flag = true;
    }
    static void Potencia_Refri_cb()
    {
        Potencia_Refri_flag = true;
    }
    static void Set_Regulator_cb()
    {
        Set_Regulator_flag = true;
    }
    static void Enable_Tapes_cb()
    {
        Enable_Tapes_flag = true;
    }
    static void Disbable_Tapes_cb()
    {
        Disbable_Tapes_flag = true;
    }
    static void Close_Contactors_cb()
    {
        Close_Contactors_flag = true;
    }
    static void Open_Contactors_cb()
    {
        Open_Contactors_flag = true;
    }
    static void Levitation_cb()
    {
        Levitation_flag = true;
    }
    static void Stop_Levitation_cb()
    {
        Stop_Levitation_flag = true;
    }
    static void Emergency_Stop_cb()
    {
        Emergency_Stop_flag = true;
    }
    static void Propulsion_cb()
    {
        Propulsion_flag = true;
    }
    static void SVPWM_cb()
    {
        SVPWM_flag = true;
    }
    static void Stop_Motor_cb()
    {
        Stop_Motor_flag = true;
    }
    static void Current_Control_cb()
    {
        Current_Control_flag = true;
    }
    static void Speed_Control_cb()
    {
        Speed_Control_flag = true;
    }
    static void Motor_Brake_cb()
    {
        Motor_Brake_flag = true;
    }
    static void Recovery_cb()
    {
        Recovery_flag = true;
    }
    
};